cargo-features = ["edition2021"]

[package]
name = "inexor-rgf-plugin-value"
description = "Inexor - Reactive Graph Flow - Plugin - Value"
version = "0.2.1"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
# async-std = { version = "1.8", features = ["attributes"] }
async-trait = "0.1"
# crossbeam = "0.8.0"
indradb-lib = "1"
lazy_static = "1.4.0"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.0.0", features = ["console_appender", "file_appender"]}
query_interface = "0.3.5"
rust-embed = { version = "6.2.0", features = ["debug-embed", "compression"] }
serde = { version = "1.0.130", features = [ "derive" ] }
serde_json = "1.0.67"
strum = { version = "0.20", features = ["derive"] }
strum_macros = "0.20"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
waiter_di = { version = "1.6.4", features = [ "async" ] }

inexor-rgf-core-frp = { git = "https://github.com/aschaeffer/inexor-rgf-core-frp.git" }
inexor-rgf-core-model = { git = "https://github.com/aschaeffer/inexor-rgf-core-model.git" }
inexor-rgf-core-reactive = { git = "https://github.com/aschaeffer/inexor-rgf-core-reactive.git" }
inexor-rgf-core-behaviour = { git = "https://github.com/aschaeffer/inexor-rgf-core-behaviour.git" }
inexor-rgf-core-plugins = { git = "https://github.com/aschaeffer/inexor-rgf-core-plugins.git" }

[lib]
# Plugins use crate-type cdylib
# https://doc.rust-lang.org/reference/linkage.html
# https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847/3
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
